[package]
name = "debug"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp-serde = "1.3.0"

[dependencies.chsl]
path = "../chsl"
features = ["serde"]

[dependencies.serde]
version = "1.0.208"
features = ["derive"]

[dependencies.sdl2]
version = "0.37.0"
features = ["unsafe_textures", "ttf"]
